# Default Github Settings
lsi: false
pygments: true
source: ./

# My setings

name: That Blog Thing

markdown: redcarpet
timezone: America/Denver

baseurl: /

exclude: [ blog.sublime-*,'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', lib]
