# default github settings
lsi: false
safe: true
source: .
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax

# Site settings
title: Nate McMaster
description: >
    Blog posts about software development, plus some other stuff.
baseurl:
url: "http://www.natemcmaster.com"
twitter_username: natemcmaster
github_username: natemcmaster
linkedin_username: natemcmaster
full_name: Nate McMaster

# Build settings
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title/
encoding: utf-8
timezone: US/Pacific
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-redirect-from
exclude:
  - Gemfile
  - .ruby-version
  - Makefile
