# Site settings
title: That Blog Thing
email: me@natemcmaster.com
description: >
    Infrequent blog posts about software development, photography, opinion, etc.
baseurl: ""
url: "http://blog.natemcmaster.com"
twitter_username: natemcmaster
github_username:  natemcmaster

# Build settings
markdown: kramdown
permalink: pretty
source: src
destination: build
timezone: America/Seattle
sass:
    sass_dir: _sass
gems:
    - jekyll-sitemap
include: [.nojekyll]