# Site settings
title: Nate McMaster
description: >
    Infrequent blog posts about software development, lifehacks, opinion, etc.
baseurl:
url: "http://www.natemcmaster.com"
twitter_username: natemcmaster
github_username:  natemcmaster
linkedin_username:  natemcmaster
full_name: Nate McMaster

# Build settings
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title/
source: src
destination: build
timezone: America/Denver
sass:
    sass_dir: _sass
gems:
    - jekyll-assets
    - jekyll-sitemap
    - jemoji
    - compass
    - jekyll-redirect-from
assets:
    cache: true
    js_compressor: no_mangle_uglifier
    css_compressor: sass
    baseurl: /assets/
    gzip: [ text/css, application/javascript ]
    sources:
        - _assets/images
        - _assets/javascripts
        - _vendors/bootstrap-sass/assets/stylesheets
        - _assets/stylesheets
        - _assets/fonts
        - _vendors/angulartics/dist

include: [.nojekyll, CNAME]

