# Default Github Settings
lsi: false
pygments: true
source: ./

# My setings

name: That Blog Thing

markdown: redcarpet
timezone: America/Denver

baseurl: /
url: blog.natemcmaster.com

exclude: [ blog.sublime-*, 'CNAME' ,'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']