# Default Github Settings
lsi: false
pygments: true
source: ./src/
destination: ./build/

# My setings

name: That Blog Thing

markdown: redcarpet
timezone: America/Denver

baseurl: /

exclude: [ blog.sublime-*,'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', lib,bower_components]

assets:
  js_compressor:  uglifier
  css_compressor: sass
  cache: true
  debug: true
  sources:
  - _assets/images
  - _assets/javascripts
  - _assets/stylesheets
  - _vendor/components
