# Site settings
title: That Blog Thing
email: me@natemcmaster.com
description: >
    Infrequent blog posts about software development, photography, opinion, etc.
baseurl: /blog
url: "http://www.natemcmaster.com/blog/"
twitter_username: natemcmaster
github_username:  natemcmaster

# Build settings
markdown: kramdown
permalink: pretty
source: src
destination: build
timezone: America/Denver
sass:
    sass_dir: _sass
gems:
    - jekyll-sitemap
    - jekyll-assets
    - jemoji
assets:
    js_compressor: uglifier
    css_compressor: sass
    baseurl: /blog/assets/
    sources:
        - _assets/images
        - _assets/javascripts
        - _assets/stylesheets
        - _vendors/angulartics/dist

include: [.nojekyll]
